name = "AvocadoAnalysis"
uuid = "0383cb07-7e66-4c81-bb29-bf3ec06167d7"
version = "0.1.0"
authors = ["vituri"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.15.8"
Statistics = "1.11.1"
julia = "1.10"
